### PR TITLE
Core pr 3 (merge with Artesis)

### PR DESCRIPTION
**Pull request by cableman**
- Updated to use moreInfo service.
- Change from black hole to virtual field.
- Fixed problem with fetching limit on moreInfo when more than 50 covers where requested.
- Updated to use the new library identifier call instead of faust.
- Clean up of JavaScript code.

Other
- Bug report sent to DBC about problem where the new method don't return covers even though the service has a cover with the old method.

### CODE REVIEW

**Comment by kasperg** [comment]
Review complete. In general this looks good. One P2 commend: It would be nice to have the client renamed from Addi to MoreInfo. Calling it Addi is obsolute and could lead to confusion.

**Comment by kasperg** [comment]
I guess the renaming will not happen right now so I consider this ready for merging with the notice regarding naming as a P2.

**Comment by cableman** [comment]
Agreed we need at some point to rename Addi to moreinfo.

**Comment by kasperg** [comment]
Merged. Thanks for all the hard work!

**Pull request merged**
